<section class="container my-5 py-5 col-6">
        <h1>Nový pojištěnec</h1>
        <form method="post">
            <div class="form-group row my-3">
                <div class="col-12 col-md-6">
                    <label class="col-form-label">Jméno</label>
                    <input type="text" name="jmeno" class="form-control col-form-label" placeholder="Jan" required = "required" value="<?php if (isset($_POST['jmeno'])) echo(htmlspecialchars($_POST['jmeno'])); ?>">
                </div>
                <div class="col-12 col-md-6">
                    <label class="col-form-label">Příjmení</label>
                    <input type="text" name="prijmeni" class="form-control col-form-label" placeholder="Novák" required = "required" value="<?php if (isset($_POST['prijmeni'])) echo(htmlspecialchars($_POST['prijmeni'])); ?>">
                </div>
            </div>
            <div class="form-group row my-3">
                <div class="col-12 col-md-6">
                    <label class="col-form-label">Email</label>
                    <input type="text" name="email" class="form-control col-form-label" placeholder="email@email.cz" required = "required" value="<?php if (isset($_POST['email'])) echo(htmlspecialchars($_POST['email'])); ?>">
                </div>
                <div class="col-12 col-md-6">
                    <label class="col-form-label">Telefon</label>
                    <input type="text" name="telefon" class="form-control col-form-label" placeholder="777666333" required = "required" value="<?php if (isset($_POST['telefon'])) echo(htmlspecialchars($_POST['telefon'])); ?>">
                </div>
            </div>
            <div class="form-group row my-3">
                <div class="col-12 col-md-6">
                    <label class="col-form-label">Ulice a číslo popisné</label>
                    <input type="text" name="ulice" class="form-control col-form-label" placeholder="Horní 28" required = "required" value="<?php if (isset($_POST['ulice'])) echo(htmlspecialchars($_POST['ulice'])); ?>">
                </div>
                <div class="col-12 col-md-6">
                    <label class="col-form-label">Město</label>
                    <input type="text" name="mesto" class="form-control col-form-label" placeholder="Brno" required = "required" value="<?php if (isset($_POST['mesto'])) echo(htmlspecialchars($_POST['mesto'])); ?>">
                </div>
            </div>
            <div class="form-group row my-3 d-flex align-items-start justify-content-end">
                <div class="col-12 col-md-6">
                    <label class="col-form-label">PSČ</label>
                    <input type="text" name="psc" class="form-control col-form-label" placeholder="69058" required = "required" value="<?php if (isset($_POST['psc'])) echo(htmlspecialchars($_POST['psc'])); ?>">
                </div>
            </div>
            <div class="form-row text-center">
                <div class="col my-2">
                    <button type="submit" class="btn btn-dark">Uložit</button>
                </div>
            </div>
        </form>
    </section>