<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/localhost" />
        <meta charset="UTF-8" />
        <title><?= $titulek ?></title>
        <meta name="description" content="<?= $popis ?>" />
        <meta name="keywords" content="<?= $klicova_slova ?>" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="stylesheet" href="styles.css" type="text/css"/>
    </head>

    <body class="d-flex flex-column min-vh-100">
    <div class="bg-grey">
        <header class="my-navbar">
            <div class="row">
                <div class="col ml-0 d-flex align-items-center">
                    <a class="navbar-brand" href="index.html">
                        <img src="images/logo.png"  class="logo-editor" width="32" height="32" alt="company-logo" />  
                    </a>
                    <div class="logo-text">
                        <a class="navbar-brand" href="index.html">
                            <p class="">FirstTimeInsurance</p>
                        </a>
                    </div>
                </div>
                <div class="col d-flex align-items-center justify-content-end">
                    <nav class="navbar navbar-expand-md">
                        
                        <button class="navbar-toggler my-1" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse text-nowrap" id="navbarSupportedContent">
                            <ul class="navbar-nav mr-auto d-flex align-items-center">
                                <li class="nav-item px-2 navbar-underline text-white">
                                <?=$_SESSION['uzivatel']['prihlasovaci_jmeno']?>
                              </li>
                              <li class="nav-item px-2 navbar-underline">
                                <a class="nav-link barva-textu-navbar" href="pojistenci">Pojištěnci</a>
                              </li>
                              <li class="nav-item px-2 navbar-underline">
                                <a class="nav-link barva-textu-navbar" href="druhPojisteni">Pojištění</a>
                            </li>
                            <li class="nav-item px-2 navbar-underline">
                              <a class="nav-link barva-textu-navbar" href="odhlaseni">Odhlásit</a>
                          </li>

                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </header>
    </div>
    <article>
    <?php foreach ($zpravy as $zprava) : ?>
        <?php if(str_contains($zprava, 'Pozor!')): ?>
            <div class="alert alert-warning" role="alert">
            <?= $zprava ?>
            </div>
        <?php else: ?>
            <div class="alert alert-success" role="alert">
            <?= $zprava ?>
        </div>
        <?php endif; ?>
        
    <?php endforeach ?> 
    <?php $this->kontroler->vypisPohled(); ?>

    </article>
    
    <footer class="mt-auto bg-grey">
    <div class="row">
        <div class="col-12 d-flex align-items-center justify-content-center">
            <p>Za pomoci ITnetwork vytvořil <span id="footer-author-name">Jan Huňař</span></p>
        </div>
    </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>
</html>