<!doctype html>
<html lang="cs-cz">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FirstTimeInsurance</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="styles.css">
</head>
  <body class="d-flex flex-column min-vh-100">
    <div class="bg-picture">
      <header class="">
          <div class="row py-1 px-5">
            <div class="col d-flex align-items-center">
              <a class="navbar-brand" href="index.html">
                <img src="images/logo.png"  class="logo-editor" width="32" height="32" alt="company-logo" />
              </a>
            </div>
              <div class="col d-flex align-items-center justify-content-end">
                  <nav class="navbar navbar-expand-md navbar-dark py-0">
                      <button class="navbar-toggler my-3 toggler-button" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                      </button>
  
                      <div class="collapse navbar-collapse text-nowrap" id="navbarSupportedContent">
                          <ul class="navbar-nav mr-auto d-flex align-items-center">
                              <li class="nav-item px-2 navbar-underline">
                                  <a class="nav-link text-dark navbar-text" href="logInPage.html">Přihlásit<span class="sr-only"></span></a>
                              </li>
                              <li class="nav-item px-2 navbar-underline">
                                  <a class="nav-link text-dark navbar-text" href="Registrace">Registrovat<span class="sr-only"></span></a>
                              </li>
                          </ul>
                      </div>
                  </nav>
              </div>
          </div>
      </header>
  
      <section class="container py-2 my-2 h-100">
          <div class="row py-5  align-items-center justify-content-start d-md-flex d-none">
              <div class="col-6 py-5 text-dark">
                <h1>FirstTimeInsurace pojišťovna</h1>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
              </div>
          </div>
      </section>
  
  </div>
    </div>
    <section class="">
        <div class="carousel-section d-none d-md-block">
            <div class="row py-5 w-100 d-flex-column align-items-center justify-content-center">
              <div class="col-10 d-flex-column align-items-center justify-content-center py-5">
                <div class="row d-flex align-items-center justify-content-between">
                  <div class="col-3 d-flex align-items-center justify-content-center">
                    <img class="img-insurance-icons" src="images/mainPageIconsInsurance/family.png" alt="">
                  </div>
                  <div class="col-3 d-flex align-items-center justify-content-center">
                    <img class="img-insurance-icons" src="images/mainPageIconsInsurance/travel.png" alt="">
                  </div>
                  <div class="col-3 d-flex align-items-center justify-content-center">
                    <img class="img-insurance-icons" src="images/mainPageIconsInsurance/car.png" alt="">
                  </div>
                  <div class="col-3 d-flex align-items-center justify-content-center">
                    <img class="img-insurance-icons" src="images/mainPageIconsInsurance/retirement.png" alt="">
                  </div>
                </div>
                <div class="row py-5">
                  <div class="col-3 d-flex align-items-center justify-content-center">
                    <h3>Rodinné pojištění</h3>
                  </div>
                  <div class="col-3 d-flex align-items-center justify-content-center">
                    <h3>Cestovní pojištění</h3>
                  </div>
                  <div class="col-3 d-flex align-items-center justify-content-center">
                    <h3>Auto-pojištění</h3>
                  </div>
                  <div class="col-3 d-flex align-items-center justify-content-center">
                    <h3>Důchodové pojištění</h3>
                  </div>
                </div>
              </div>
            </div>
        </div>
    <div class="container">
        <div class="row justify-content-center align-items-center my-3 py-5">
            <div class="col-12 col-md-4 text-center d-none d-lg-flex">
                <img class="img-services-mainpage" src="images/mainPageInformations/customer.png" alt="customerIcon">
            </div>
            <div class="col-8 text-justify">
                <h2>Řešení šité na míru</h2>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Mauris metus. Fusce consectetuer risus a nunc. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.</p>
            </div>
        </div>
        <div class="row justify-content-center align-items-center my-3 py-5">
            <div class="col-8 text-justify">
                <h2>Podpora</h2>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Mauris metus. Fusce consectetuer risus a nunc. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.</p>
            </div>
            <div class="col-12 col-md-4 text-center d-none d-lg-flex">
                <img class="img-services-mainpage" src="images/mainPageInformations/support.png" alt="supportIcon">
            </div>
        </div>
    </div>
    </section>
<footer class="bg-grey d-flex justify-content-center align-items-end">
    <div class="row pt-2">
        <div class="col d-flex align-items-end justify-content-center">
                    <p>Za pomocí IT network vytvořil Jan Huňař</p>
        </div>
    </div>
</footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>